apiVersion: apps/v1
kind: pod
metadata:
  name: pod-lifetime
  annotations:
    pod.kubernetes.io/lifetime: 300s 
spec:
  validationFailureAction: audit
  background: true
  rules:
  - name: pods-lifetime
    match:
      resources:
        kinds:
        - Pod
    validate:
      message: "Pod lifetime exceeds limit of 300s"
      deny:
        conditions:
        - key: "{{ request.object.metadata.annotations.\"pod.kubernetes.io/lifetime\" }}"
          operator: GreaterThan
          value: "300s"
