apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: demo
      tier: {{ .Values.tier }}
      team: {{ .Values.team }}
  template:
    metadata:
      annotations:
        pod.kubernetes.io/lifetime: 300s
      labels:
        app: demo
        tier: {{ .Values.tier }}
        team: {{ .Values.team }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.docker_image }}
        env:
          - name: REMOTE_EXEC
            value:  "true"
          - name: APP
            value: {{ .Chart.Name }}
          - name: COMMIT_AUTHOR
            value: {{ .Values.author }}
          - name: REAPER_NAMESPACES
            value: {{ .Release.Namespace }}
          - name: MAX_REAP_COUNT_PER_RUN
            value: {{ .Values.maxReapCountPerRun | default 30 | quote}}
          - name: REAP_EVICTED_PODS
            value: {{ .Values.reapEvictedPods | default false | quote}}
          - name: CRON_JOB
            value: {{ .Values.cronJob | default false | quote}} 
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 50m
            memory: 128Mi
