apiVersion: v1
kind: Pod
metadata:
  name: frontend
  annotations:pod.kubernetes.io/lifetime: 300s
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        memory: "64Mi"
      limits:
        memory: "128Mi"
